insert into transactions values ('Козьма Александра Петровна', 37);
insert into transactions values ('Окладникова Полина Евгеньевна', 461);
insert into transactions values ('Андреев Яков Евгеньевич', 542);
insert into transactions values ('Самайкин Егор Сергеевич', 262);
insert into transactions values ('Зубаревич Ксения Владимировна', 73);
insert into transactions values ('Зубаревич Ксения Владимировна', 797);
insert into transactions values ('Хоанг Вьет Зунг', 156);
insert into transactions values ('Конакова Анастасия Андреевна', 57);
insert into transactions values ('Козьма Александра Петровна', 549);
insert into transactions values ('Медведев Константин Станиславович', 977);
insert into transactions values ('Ястребов Андрей', 159);
insert into transactions values ('Ястребов Андрей', 758);
insert into transactions values ('Бунтов Станислав Андреевич', 700);
insert into transactions values ('Зубаревич Ксения Владимировна', 252);
insert into transactions values ('Лёвин Василий Сергеевич', 617);
insert into transactions values ('Медведев Константин Станиславович', 690);
insert into transactions values ('Самайкин Егор Сергеевич', 556);
insert into transactions values ('Бунтов Станислав Андреевич', 697);
insert into transactions values ('Окладникова Полина Евгеньевна', 630);
insert into transactions values ('Козьма Александра Петровна', 225);
insert into transactions values ('Козьма Александра Петровна', 946);
insert into transactions values ('Хоанг Вьет Зунг', 548);
insert into transactions values ('Козьма Александра Петровна', 816);
insert into transactions values ('Пробочкин Андрей Михайлович', 298);
insert into transactions values ('Ястребов Андрей', 832);
insert into transactions values ('Андреев Яков Евгеньевич', 934);
insert into transactions values ('Самайкин Егор Сергеевич', 635);
insert into transactions values ('Пробочкин Андрей Михайлович', 742);
insert into transactions values ('Тарасов Никита Евгеньевич', 43);
insert into transactions values ('Перевощиков Яков Эдуардович', 996);
insert into transactions values ('Шняк Дарья Александровна', 288);
insert into transactions values ('Андреев Яков Евгеньевич', 523);
insert into transactions values ('Конакова Анастасия Андреевна', 994);
insert into transactions values ('Окладникова Полина Евгеньевна', 287);
insert into transactions values ('Шняк Дарья Александровна', 202);
insert into transactions values ('Козьма Александра Петровна', 163);
insert into transactions values ('Окладникова Полина Евгеньевна', 897);
insert into transactions values ('Самайкин Егор Сергеевич', 512);
insert into transactions values ('Шняк Дарья Александровна', 335);
insert into transactions values ('Капустин Александр Евгеньевич', 34);
insert into transactions values ('Козьма Александра Петровна', 512);
insert into transactions values ('Перевощиков Яков Эдуардович', 432);
insert into transactions values ('Лёвин Василий Сергеевич', 922);
insert into transactions values ('Шняк Дарья Александровна', 857);
insert into transactions values ('Ястребов Андрей', 31);
insert into transactions values ('Самайкин Егор Сергеевич', 700);
insert into transactions values ('Зубаревич Ксения Владимировна', 412);
insert into transactions values ('Хоанг Вьет Зунг', 948);
insert into transactions values ('Тарасов Никита Евгеньевич', 47);
insert into transactions values ('Медведев Константин Станиславович', 204);
insert into transactions values ('Конакова Анастасия Андреевна', 195);
insert into transactions values ('Хоанг Вьет Зунг', 864);
insert into transactions values ('Андреев Яков Евгеньевич', 120);
insert into transactions values ('Медведев Константин Станиславович', 529);
insert into transactions values ('Бунтов Станислав Андреевич', 215);
insert into transactions values ('Конакова Анастасия Андреевна', 426);
insert into transactions values ('Бунтов Станислав Андреевич', 610);
insert into transactions values ('Окладникова Полина Евгеньевна', 245);
insert into transactions values ('Ястребов Андрей', 959);
insert into transactions values ('Лёвин Василий Сергеевич', 415);
insert into transactions values ('Самайкин Егор Сергеевич', 632);
insert into transactions values ('Андреев Яков Евгеньевич', 469);
insert into transactions values ('Бунтов Станислав Андреевич', 104);
insert into transactions values ('Зубаревич Ксения Владимировна', 252);

insert into dict values ('0', 'zero');
insert into dict values ('1', 'one');
insert into dict values ('2', 'two');
insert into dict values ('3', 'three');
insert into dict values ('4', 'four');
insert into dict values ('5', 'five');
insert into dict values ('6', 'six');
insert into dict values ('7', 'seven');
insert into dict values ('8', 'eight');
insert into dict values ('9', 'nine');

insert into golden values (1), (2), (4), (8), (16), (32), (64), (128), (256), (512), (1024);
